### ISSUE TITLE
support having in sql

### ISSUE THREAD

**Issue by ni-ze** [alibaba/rsqldb#46]
sql tamplate：
```sql
  SELECT [ ALL | DISTINCT ]{ * | projectItem [, projectItem ]* }
  FROM tableExpression
  [ WHERE booleanExpression ]
  [ GROUP BY { groupItem [, groupItem ]* } ]
  [ HAVING booleanExpression ];
```
test sql:
```sql
SELECT Customer,SUM(OrderPrice) FROM XXX
GROUP BY Customer
HAVING SUM(OrderPrice)<2000;
```
test data:
Customer | OrderPrice
-- | --
Bush | 1000
Carter | 1600
Bush | 700
Bush | 300
Adams | 2000
Carter | 100

expected result:
<br class="Apple-interchange-newline">

Customer | SUM（OrderPrice）
-- | --
Carter | 1700

**Comment by TheR1sing3un** [comment]
Hi~ Could I hava a try?

**Comment by ni-ze** [comment]
sure, of cause.
